print("Copying the odd lines of a file to a new file")
print("***********************************")
f1=open("fileline1.txt","r")
f2=open("filelline2.txt","w")
l=f1.readlines()
type(l)
for i in range(0,len(l)):
 if(i%2!=0):
  f2.write(l[i])
f1.close()
f2.close()
f1=open("fileline1.txt","r")
print("Old file content")
print(f1.read())
f2=open("filelline2.txt","r")
print("New file content")
print(f2.read())
f1.close()
f2.close()